tz-wrapped/tezos-btc

.crossref-verifier.yaml
README.md

The commands for building with nix changed when we switched to haskell.nix in https://github.com/serokell/tezos-btc/pull/78
None
really minor.

Update README instructions for building the project with nix

---

ChangeLog.md
app/Main.hs
package.yaml
release.nix
src/CLI/Parser.hs
src/Client/API.hs
src/Client/IO.hs
src/Lorentz/Contracts/Multisig.hs
src/Lorentz/Contracts/TZBTC/Impl.hs
src/Lorentz/Contracts/TZBTC/Test.hs
src/Lorentz/Contracts/TZBTC/Types.hs
src/Lorentz/Contracts/TZBTC/V0.hs
src/Util/AbstractIO.hs
src/Util/MultiSig.hs
stack.yaml
stack.yaml.lock
test/Test/Client.hs
test/Test/IO.hs
test/Test/MultiSig.hs
test/Test/TZBTC.hs
test/TestM.hs

Bring the previously disabled roundtrip test back to life.
I'm not sure taken solution is sensible, but don't see a viable alternative.
https://issues.serokell.io/issue/TBTC-89
really minor.

[TBTC-89] Enable rountrip test

---

src/Lorentz/Contracts/TZBTC/V0.hs

Problem: Contract documentation doesn't specify the process of the
deployment, however, it's important to upgrade originated V0 to V1,
otherwise, contract will be unusuable.
Solution: Add paragraph about deployment to the generated contract
documentation.
Resolves #124
really minor.

[#124] Clarify contract deployment process

---

ci.nix
nix/sources.json

Makes sure that haskell.nix revision used in CI is the same as most of our other projects have, to reduce number of ghc builds
https://issues.serokell.io/issue/OPS-1023
really minor.

[OPS-1023] CI: update dependencies, pin hackage and stackage indexes independently

---

README.md

Problem: A person who uses this smart contract must be aware of
some important things: potential security vulnerabilities and
what can be done with their tokens.
Solution: Add chapter that mentions the unsafety of the 'approve'
entrypoint and explains how users' balances and transferring abilities
can be affected by the contract owner and operators.
Resolves #128
really minor.

[#128] Add chapter about security and trust model

---

.buildkite/pipeline.yml
ci.nix

We already have a project that has autoreleasing and it's quite
convenient when we want to have a release with some set of assets, so
we're going to use autoreleasing in tzbtc as well.
Resolves #138
really minor.

[#138] Autoreleasing

---

.buildkite/pipeline.yml

Problem: It was broken in #143 and autoreleasing doesn't work now.
Solution: Fix step filter.
Resolves None
really minor.

Fix filter for packaging step in CI

---

.buildkite/pipeline.yml
nix/sources.json
package.yaml
src/Client/Env.hs
src/Client/IO.hs
src/Lorentz/Contracts/Metadata.hs
stack.yaml
stack.yaml.lock
test/Test/IO.hs
test/Test/Smoke.hs
test/TestM.hs

Problem: New protocol arrived.
Solution: Run network tests on 008 local-chain and edonet.
Based on https://gitlab.com/morley-framework/morley/-/merge_requests/772
https://issues.serokell.io/issue/TM-491
really minor.

Add 008 network tests 

---

.buildkite/pipeline.yml

Problem: $PWD interpolates instantly in the pipeline, thus the data
directory provided scheduled build is invalid.
Solution: Escape this variable.
Resolves None
really minor.

Escape $PWD shell variable

---

.buildkite/pipeline.yml
ci.nix
nix/sources.json
nix/sources.nix
tzbtc.nix

Updates dependencies used by CI to keep them up to date
Related issue: https://issues.serokell.io/issue/OPS-1174

CI: bump dependencies

---

hpack/definitions.yaml
nix/sources.json
src/Lorentz/Contracts/Metadata.hs
src/Lorentz/Contracts/TZBTC/Common/Types.hs
src/Lorentz/Contracts/TZBTC/V1/Impl.hs
src/Lorentz/Contracts/TZBTC/V1/ManagedLedger/Impl.hs
src/Lorentz/Contracts/TZBTC/V2/Types.hs
stack.yaml
stack.yaml.lock
test/Test/Smoke.hs
test/Test/TZBTC.hs

Problem: We want to check whether this repo can be used with the latest
morley and new GHC version.
Solution: Bump dependencies and make required changes in the code.
Depends on:
* https://gitlab.com/morley-framework/morley-upgradeable/-/merge_requests/9
* https://gitlab.com/morley-framework/morley-multisig
https://issues.serokell.io/issue/TM-523
really minor.

[TM-523] Bump morley and other deps

---

.buildkite/pipeline.yml
nix/sources.json

Problem: New Tezos protocol arrived, we'd like to run tests for our
projects on it.
Solution: Add 009-related jobs to CI config.
https://issues.serokell.io/issue/TM-525
really minor.

[TM-525] Florencenet in CI

---

.buildkite/pipeline.yml

Problem: protocol 008 has become obsolete.
Solution: remove tests for 008 local chain and edo2net from the CI.
Resolves part of TM-546
really minor.

Remove edo2net tests

---

.buildkite/pipeline.yml
nix/sources.json

Problem: Tezos has a new protocol and we should check if this project is
compatible with it.
Solution: Add local-chain and scheduled testnet jobs for the new
protocol to the CI configuration.
https://issues.serokell.io/issue/TM-595
really minor.

[Chore] Add hangzhou CI steps

---

.buildkite/pipeline.yml
ci.nix
nix/sources.json
stack.yaml
stack.yaml.lock
test/Test/Smoke.hs
test/TestM.hs

Problem: Tezos has a new protocol and we should check if this project is
compatible with it.
Solution: Replace hangzhou local-chain and scheduled testnet jobs with ithaca
in the CI configuration.
Currently based on https://gitlab.com/morley-framework/morley-upgradeable/-/merge_requests/18 and https://gitlab.com/morley-framework/morley-infra/-/merge_requests/4.
https://issues.serokell.io/issue/TM-628
really minor.

[Chore] Replace hangzhou steps with ithaca in CI

---

.buildkite/pipeline.yml
ChangeLog.md
README.md
app/Main.hs
bats/tzbtc.bats
ci.nix
nix/sources.json
package.yaml
release.nix
src/CLI/L1AddressOrAlias.hs
src/CLI/Parser.hs
src/Client/Env.hs
src/Client/IO.hs
src/Client/Main.hs
src/Client/Parser.hs
src/Client/Types.hs
src/Lorentz/Contracts/TZBTC/V0.hs
src/Lorentz/Contracts/TZBTC/V1/Types.hs
src/Lorentz/Contracts/TZBTC/V2/Types.hs
src/Util/MultiSig.hs
stack.yaml
stack.yaml.lock
test/Test/IO.hs
test/Test/Migration.hs
test/Test/MultiSig.hs
test/Test/Smoke.hs
test/Test/TZBTC.hs
test/TestM.hs

Problem: new versions of morley &c are out.
Solution: update.
One quirk is we want to have some parameters accept either smart contract or implicit address address/alias. In morley we solved this issue with splitting options into two, but after a bit of discussion we decided to instead encode alias kind into the alias string itself. Hence, a temporary module "CLI.L1AddressOrAlias" implements that logic until it's moved into Morley.
Part of https://issues.serokell.io/issue/TM-659
really minor.

[Chore] Bump morley &c

---

ChangeLog.md
package.yaml
release.nix

Bumps the version number to prepare for a new release, because one significant user-facing and several other changes have been made since the last one.
None
really minor.

[Chore] Prepare a new release

---

.buildkite/pipeline.yml
ChangeLog.md
ci.nix
client/Main.hs
nix/sources.json
package.yaml
release.nix
src/CLI/L1AddressOrAlias.hs
src/Client/Env.hs
src/Client/IO.hs
src/Client/Main.hs
src/Client/Parser.hs
src/Client/Types.hs
src/Lorentz/Contracts/TZBTC/Common/Types.hs
src/Lorentz/Contracts/TZBTC/Preprocess.hs
src/Util/MultiSig.hs
stack.yaml
test/Test/IO.hs
test/Test/Smoke.hs
test/Test/TZBTC.hs
test/TestM.hs

Update to new versions of morley &c. ~~This is WIP, I want to see how many network tests I broke.~~
Part of TM-667
really minor.

[Chore] Bump morley&c

---

README.md

Adds a warning for the upcoming Morley deprecation to the relevant docs.
None
really minor.

[Chore] Add warnings for the upcoming deprecation of Morley

---

.buildkite/pipeline.yml
ChangeLog.md
app/Main.hs
flake.lock
package.yaml
src/Client/Env.hs
src/Lorentz/Contracts/TZBTC/Common/Types.hs
src/Lorentz/Contracts/TZBTC/V1/Impl.hs
src/Util/MultiSig.hs
stack.yaml
test/Test/IO.hs
test/Test/TZBTC.hs
test/TestM.hs

Problem: we want to test on Nairobinet
Solution: bump morley-infra, add Nairobinet CI jobs
Part of [TM-680](https://issues.serokell.io/issue/TM-680)
really minor.

[Chore] Add Nairobinet tests to CI
